<?php

namespace Database\Seeders\General\System;

use App\Models\General\System\Module;
use App\Models\General\System\SubModule;
use Illuminate\Database\Seeder;

class SubModuleSeeder extends Seeder
{
    public function run(): void
    {
        $inventoryModule = Module::where('code', 'INV')->first();
        $salesModule = Module::where('code', 'SLS')->first();
        $financeModule = Module::where('code', 'FIN')->first();
        $hrModule = Module::where('code', 'HRM')->first();
        $crmModule = Module::where('code', 'CRM')->first();
        $projectModule = Module::where('code', 'PRM')->first();
        $warehouseModule = Module::where('code', 'WHS')->first();
        $generalModule = Module::where('code', 'GEN')->first();
        $contractsModule = Module::where('code', 'CNT')->first();

        SubModule::insert([
            // Inventory Management Submodules
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-STK",
                'name' => 'Stock Tracking',
                'short' => 'Stock',
                'description' => 'Tracks stock additions, removals, levels, and adjustments.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-WAR",
                'name' => 'Warehousing',
                'short' => 'Warehouse',
                'description' => 'Manages warehouses and stock locations.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-BCH",
                'name' => 'Batch & Lot Tracking',
                'short' => 'Batch',
                'description' => 'Tracks product batches and lot numbers.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-RPT",
                'name' => 'Inventory Reports & Analytics',
                'short' => 'Reports',
                'description' => 'Provides reports on stock levels and inventory valuation.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-VAL",
                'name' => 'Inventory Valuation Methods',
                'short' => 'Valuation',
                'description' => 'Manages valuation methods like FIFO, LIFO, and Weighted Average.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-REP",
                'name' => 'Stock Replenishment & Forecasting',
                'short' => 'Replenishment',
                'description' => 'Forecasts stock needs and manages reorder points.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $inventoryModule->id,
                'code' => "{$inventoryModule->code}-AUD",
                'name' => 'Inventory Audits',
                'short' => 'Audits',
                'description' => 'Tracks stock counts and adjustments.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // Sales & Purchasing Submodules
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-ORD",
                'name' => 'Sales Orders',
                'short' => 'Orders',
                'description' => 'Handles customer sales orders from creation to invoicing.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-QTN",
                'name' => 'Quotations',
                'short' => 'Quotations',
                'description' => 'Manages customer quotations and conversions to sales orders.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-PUR",
                'name' => 'Purchase Orders',
                'short' => 'Purchasing',
                'description' => 'Tracks purchase orders and supplier invoicing.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-INV",
                'name' => 'Invoicing',
                'short' => 'Invoicing',
                'description' => 'Handles invoicing for both customers and suppliers.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-SUP",
                'name' => 'Supplier Management',
                'short' => 'Suppliers',
                'description' => 'Tracks supplier details and procurement terms.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $salesModule->id,
                'code' => "{$salesModule->code}-RPT",
                'name' => 'Reports & Analytics',
                'short' => 'Reports',
                'description' => 'Provides insights on sales, purchase orders, and inventory levels.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // Finance & Accounting Submodules
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-GL",
                'name' => 'General Ledger',
                'short' => 'Ledger',
                'description' => 'Tracks all financial transactions.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-AR",
                'name' => 'Accounts Receivable',
                'short' => 'A/R',
                'description' => 'Manages customer invoices and incoming payments.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-AP",
                'name' => 'Accounts Payable',
                'short' => 'A/P',
                'description' => 'Handles supplier invoices and payments.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-BUD",
                'name' => 'Budgeting',
                'short' => 'Budgeting',
                'description' => 'Tracks and compares budget against actual financial data.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-MCY",
                'name' => 'Multi-Currency',
                'short' => 'Currencies',
                'description' => 'Manages transactions in multiple currencies.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-TAX",
                'name' => 'Tax Management',
                'short' => 'Taxes',
                'description' => 'Manages tax configurations and calculations.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $financeModule->id,
                'code' => "{$financeModule->code}-RPT",
                'name' => 'Financial Reports',
                'short' => 'Reports',
                'description' => 'Generates financial statements and reports.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // HR Management Submodules
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-EMP",
                'name' => 'Employee Management',
                'short' => 'Employees',
                'description' => 'Handles employee records and profiles.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-PAY",
                'name' => 'Payroll Management',
                'short' => 'Payroll',
                'description' => 'Manages employee payroll, taxes, and deductions.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-LV",
                'name' => 'Leave Management',
                'short' => 'Leave',
                'description' => 'Tracks leave requests, balances, and approvals.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-ATT",
                'name' => 'Attendance & Timesheets',
                'short' => 'Attendance',
                'description' => 'Records employee attendance and timesheets.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-PERF",
                'name' => 'Performance Management',
                'short' => 'Performance',
                'description' => 'Tracks performance appraisals and goals.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-TRN",
                'name' => 'Training & Development',
                'short' => 'Training',
                'description' => 'Manages employee training programs and development.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-REC",
                'name' => 'Recruitment & Onboarding',
                'short' => 'Recruitment',
                'description' => 'Handles job postings, applicant tracking, and onboarding.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-CMP",
                'name' => 'Compliance & Legal',
                'short' => 'Compliance',
                'description' => 'Ensures compliance with labor laws and company policies.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $hrModule->id,
                'code' => "{$hrModule->code}-RPT",
                'name' => 'HR Analytics & Reporting',
                'short' => 'Reports',
                'description' => 'Generates reports on HR metrics and analytics.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // CRM Submodules
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-DB",
                'name' => 'Customer Database',
                'short' => 'Database',
                'description' => 'Stores customer profiles and contact information.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-PIPE",
                'name' => 'Sales Pipeline Management',
                'short' => 'Pipeline',
                'description' => 'Manages leads and sales opportunities.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-INTER",
                'name' => 'Customer Interactions',
                'short' => 'Interactions',
                'description' => 'Tracks communications with customers.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-MKT",
                'name' => 'Marketing Campaigns',
                'short' => 'Marketing',
                'description' => 'Runs targeted marketing campaigns for leads and customers.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-SUPP",
                'name' => 'Customer Support',
                'short' => 'Support',
                'description' => 'Handles support tickets and customer service.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-RPT",
                'name' => 'CRM Reports & Analytics',
                'short' => 'Reports',
                'description' => 'Generates reports on CRM activities.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $crmModule->id,
                'code' => "{$crmModule->code}-AUT",
                'name' => 'Automation & Workflow Management',
                'short' => 'Automation',
                'description' => 'Automates tasks and workflows within CRM.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // Project Management Submodules
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-PLAN",
                'name' => 'Project Planning',
                'short' => 'Planning',
                'description' => 'Defines project scope, budget, and deadlines.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-TASK",
                'name' => 'Task Management',
                'short' => 'Tasks',
                'description' => 'Handles tasks and assignments within projects.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-MLST",
                'name' => 'Milestones',
                'short' => 'Milestones',
                'description' => 'Tracks project milestones and phases.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-COL",
                'name' => 'Collaboration & Communication',
                'short' => 'Collaboration',
                'description' => 'Supports team collaboration and communications.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-RES",
                'name' => 'Resource Management',
                'short' => 'Resources',
                'description' => 'Allocates and tracks resources for projects.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],  [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-TIME",
                'name' => 'Time Tracking',
                'short' => 'Time',
                'description' => 'Tracks time spent on tasks and projects.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-RPT",
                'name' => 'Project Reports & Analytics',
                'short' => 'Reports',
                'description' => 'Generates reports on project progress and performance.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $projectModule->id,
                'code' => "{$projectModule->code}-RISK",
                'name' => 'Risk Management',
                'short' => 'Risk',
                'description' => 'Identifies and tracks project risks and mitigations.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            // Contracts Management Submodules
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-CUS",
                'name' => 'Customer Contracts',
                'short' => 'Customer',
                'description' => 'Manages contracts with customers, including renewals and terminations.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-SUP",
                'name' => 'Supplier Contracts',
                'short' => 'Supplier',
                'description' => 'Tracks contracts with suppliers and ensures compliance.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-TP",
                'name' => 'Third-Party Contracts',
                'short' => 'Third-Party',
                'description' => 'Manages contracts with third-party vendors and service providers.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-CMP",
                'name' => 'Contract Compliance & Legal',
                'short' => 'Compliance',
                'description' => 'Ensures all contracts meet legal standards and tracks approvals.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-TEMPL",
                'name' => 'Contract Templates & Document Management',
                'short' => 'Templates',
                'description' => 'Manages contract templates and document storage.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-REN",
                'name' => 'Contract Renewals & Amendments',
                'short' => 'Renewals',
                'description' => 'Handles contract renewals and amendments, ensuring up-to-date records.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
            [
                'module_id' => $contractsModule->id,
                'code' => "{$contractsModule->code}-RPT",
                'name' => 'Contract Reports & Analytics',
                'short' => 'Reports',
                'description' => 'Generates analytics and reports on contract compliance and status.',
                'component' => null,
                'view' => null,
                'model' => null,
                'controller' => null,
            ],
        ]);
    }
}
